gcam: Use RELAX_USES_LIBRARY_CHECK
FAILED: out/target/common/obj/APPS/DMGC_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/DMGC_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/D
MGC_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt 	   	   	   	   	  device/xiaomi/x/DMGC/DMGC.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [com.google.android.gestureservice, com.google.android.camera2, com.google.android.camera.experimental2015, com.google.android.camera.experimental2016, com.google.android.camera.experimental20
17, com.google.android.camera.experimental2018, com.google.android.camera.experimental2019, com.google.android.wearable]
	- tags in the manifest (device/xiaomi/x/DMGC/DMGC.apk):
		uses-library-not-required:'com.google.android.gestureservice'		uses-library-not-required:'com.google.android.camera2'		uses-library-not-required:'com.google.android.camera.experimental2015'		uses-l
ibrary-not-required:'com.google.android.camera.experimental2016'		uses-library-not-required:'com.google.android.camera.experimental2017'		uses-library-not-required:'com.google.android.camera.experimental2018'		u
ses-library-not-required:'com.google.android.camera.experimental2019'		uses-library-not-required:'com.google.android.wearable'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- see build/make/Changes.md for details

Signed-off-by: OdSazib <odsazib@gmail.com>